

export const colourOptions = [
  { value: 'ocean', label: 'Ocean', color: '#00B8D9', isFixed: true },
  { value: 'blue', label: 'Blue', color: '#0052CC', isDisabled: true },
  { value: 'purple', label: 'Purple', color: '#5243AA' },
  { value: 'red', label: 'Red', color: '#FF5630', isFixed: true },
  { value: 'orange', label: 'Orange', color: '#FF8B00' },
  { value: 'yellow', label: 'Yellow', color: '#FFC400' },
  { value: 'green', label: 'Green', color: '#36B37E' },
  { value: 'forest', label: 'Forest', color: '#00875A' },
  { value: 'slate', label: 'Slate', color: '#253858' },
  { value: 'silver', label: 'Silver', color: '#666666' },
];
export const channelTopicOptions=[
  { value: 'Activism', label: 'Activism', color: '#00B8D9'},
  { value: 'Addiction Support', label: 'Addiction Support', color: '#00B8D9'},
  { value: 'Animals And Pets', label: 'Animals And Pets', color: '#00B8D9'},
  { value: 'Anime', label: 'Anime', color: '#00B8D9'},
  { value: 'Art', label: 'Art', color: '#00B8D9'},
  { value: 'Beauty And Makeup', label: 'Beauty And Makeup', color: '#00B8D9'},
  { value: 'Business Economics, and Finance', label: 'Business Economics, and Finance', color: '#00B8D9'},
  { value: 'Careers', label: 'Careers', color: '#00B8D9'},
  { value: 'Cars and Motor Vehicles', label: 'Cars and Motor Vehicles', color: '#00B8D9'},
  { value: 'Celebrity', label: 'Celebrity', color: '#00B8D9'},
  { value: 'Crafts and DIY', label: 'Crafts and DIY', color: '#00B8D9'},
  { value: 'Crypto', label: 'Crypto', color: '#00B8D9'},
  { value: 'Culture,Race,and Ethnicity', label: 'Culture,Race,and Ethnicity', color: '#00B8D9'},
  { value: 'Ethics and Phillisophy', label: 'Ethics and Phillisophy', color: '#00B8D9'},
  { value: 'Family and Relationships', label: 'Family and Relationships', color: '#00B8D9'},
  { value: 'Fashion', label: 'Fashion', color: '#00B8D9'},
  { value: 'Fitness and Nutrition', label: 'Fitness and Nutrition', color: '#00B8D9'},
  { value: 'Food and Drink', label: 'Food and Drink', color: '#00B8D9'},
  { value: 'Funny/Hunter', label: 'Funny/Hunter', color: '#00B8D9'},
   { value: 'Gaming', label: 'Gaming', color: '#00B8D9'},
  { value: 'Gender', label: 'Gender', color: '#00B8D9'},
  { value: 'History', label: 'History', color: '#00B8D9'},
  { value: 'Hobbies', label: 'Hobbies', color: '#00B8D9'},
  { value: 'Home and Garden', label: 'Home and Garden', color: '#00B8D9'},
  { value: 'Internet Culture and Memes', label: 'Internet Culture and Memes', color: '#00B8D9'},
  { value: 'Law', label: 'Law', color: '#00B8D9'},
  { value: 'Learning and Education', label: 'Learning and Education', color: '#00B8D9'},
  { value: 'Marketplace and Deals', label: 'Marketplace and Deals', color: '#00B8D9'},
  { value: 'Mature Themes and Adult Content', label: 'Mature Themes and Adult Content', color: '#00B8D9'},
  { value: 'Medical and Mental Health', label: 'Medical and Mental Health', color: '#00B8D9'},
  { value: 'Men`s Health', label: 'Men`s Health', color: '#00B8D9'},
   { value: 'Meta/Reddit', label: 'Meta/Reddit', color: '#00B8D9'},
   { value: 'Military', label: 'Military', color: '#00B8D9'},
   { value: 'Movies', label: 'Movies', color: '#00B8D9'},
   { value: 'Music', label: 'Music', color: '#00B8D9'},
   { value: 'OutDoors and Nature', label: 'OutDoors and Nature', color: '#00B8D9'},
   { value: 'Place', label: 'Place', color: '#00B8D9'},
   { value: 'Podcasts and Streamers', label: 'Podcasts and Streamers', color: '#00B8D9'},
   { value: 'Politics', label: 'Politics', color: '#00B8D9'},
   { value: 'Programming', label: 'Programming', color: '#00B8D9'},
   { value: 'Reading, Writing, and literature', label: 'Reading, Writing, and literature', color: '#00B8D9'},
   { value: 'Religion and Spirituality', label: 'Religion and Spirituality', color: '#00B8D9'},
   { value: 'Science', label: 'Science', color: '#00B8D9'},
   { value: 'Sexual orientation', label: 'Sexual orientation', color: '#00B8D9'},
   { value: 'Sports', label: 'Sports', color: '#00B8D9'},
   { value: 'Tabletop Games', label: 'Tabletop Games', color: '#00B8D9'},
   { value: 'Technology', label: 'Technology', color: '#00B8D9'},
   { value: 'Television', label: 'Television', color: '#00B8D9'},
   { value: 'Trauma support', label: 'Trauma support', color: '#00B8D9'},
   { value: 'Travel', label: 'Travel', color: '#00B8D9'},
   { value: 'Women`s Health', label: 'Women`s Health', color: '#00B8D9'},
   { value: 'None of these topics', label: 'None of these topics', color: '#00B8D9'},


 

 
]
